title: Sharing Room
author: Yangyuanchen Liu
email: lyyc199586@sjtu.edu.cn
description: >
  © 2019-present, Yangyuanchen Liu.  This is a personal website and tech blog.
  Sharing Room is all about sharing, I will record share academic and technical 
  notes on this website.

show_excerpts: false

disqus:
    shortname: lyyc199586
    
# Minima date format
minima:
  date_format: "%b %-d, %Y"

  

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  lyyc199586
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: 杨元琛-刘-239148120
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Build settings
theme: minima 
#theme: jekyll-theme-minimal

markdown: kramdown

plugin:
 - jekyll-feed
 - jekyll-seo-tag